name: ProFolio CI

on:
  push:
    branches:
      - feature/** 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install dependencies
        run: cd api && npm i && cd ../frontend && npm i

      # Build the AceBook app
      - name: Build AceBook app
        run: cd frontend && npm run build

      # Run tests
      - name: Run tests
        run: |
          # Start MongoDB container
          docker run -d -p 27017:27017 --name mongodb mongo:6.0
          echo "Waiting for MongoDB to start..."
          sleep 10          # give MongoDB a few seconds to initialize
          
          # Set up environment variables
          echo 'VITE_BACKEND_URL="http://localhost:3000"' > frontend/.env
          echo 'MONGODB_URL="mongodb://0.0.0.0/acebook"' > api/.env
          echo 'NODE_ENV="development"' >> api/.env
          echo 'JWT_SECRET="secret"' >> api/.env
          
          # Run tests
          # Backend using Jest
          cd api && npm test -- --watchAll=false
          # Frontend tests with Vitest, so can't use --watchAll flag
          cd ../frontend && npm test -- --run